### ISSUE TITLE
MAC always null 

### ISSUE THREAD

**Issue by AnD010** [mavris/MacFinder#1]
Hi!,
First thanks for your time, 
I have a question... is so strange.... 
A year and a half ago... I make this question 
http://stackoverflow.com/questions/29618331/getting-arp-table-on-iphone-ipad-always-return-nil-the-mac
I needed the MAC for a private project... now this project is neccesary...
But I have a problem...always my mac is null, I observe in debug that always in the function
`sysctl(mib, 6, NULL, &needed, NULL, 0) < 0)`
needed has a size 128... and this is wrong... always return  mac null...
I download your proyect and I have the same result...insert my IP and I have MAC null...
If  I insert ip router MAC is correct in my and your code
The most strange is... I have install fing app( show all macs/ips connect to wifi ), well..if starting this app and check the red... i can see mac and ip of my device all ok,
then run your app or my code... and sourprise.... I have correct  MAC result!! is so crazy!!
now If debug the code I can seee neede has more size... 512 or 32768....

I don´t understand nothing... I´m testing with iphone 5s and ios version 9.2.1  Xcode 8

regards!

**Comment by mavris** [comment]
Hi,
The reason why the code works after Fing is that because Fing already built the ARP table and MacFinder can get the MAC Address using the IP. I never noticed that issue because I am using the MacFinder with another open source project [MMLanScan](https://github.com/mavris/MMLanScan) which is scanning the lan network and retrieving the MAC Address. So my suggestion is first ping the hostname and then use MAC Finder. You can use the code from [MMLanScan](https://github.com/mavris/MMLanScan). After implementing that feature send me a pull request for MacFinder if want.

**Comment by AnD010** [comment]
Hi! 
Thanks you so much, 
Yes, Tomorrow, I will do that feature and send you a pull request. 

Regards!
